# Generated by Django 5.0.2 on 2024-03-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=30)),
                ('perteneciente', models.IntegerField()),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('empresa', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['dni'],
            },
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deudor', models.CharField(max_length=30)),
                ('perteneciente', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('monto', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
            ],
            options={
                'ordering': ['dni'],
            },
        ),
    ]
