# Generated by Django 5.0.2 on 2024-03-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cheque',
            new_name='Cheques',
        ),
    ]
