# Generated by Django 5.0.2 on 2024-03-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_cheque_cheques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
