# Generated by Django 5.0.2 on 2024-03-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_cheques_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheques',
            name='fecha',
            field=models.DateField(),
        ),
    ]
